name: Docs Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'rose-pyforce/pyforce/**'
      - 'docs/**'
      - 'rose-pyforce/pyproject.toml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ./rose-pyforce
          pip install sphinx myst-parser nbsphinx sphinx-proof \
                      sphinxcontrib-bibtex==2.5.0 ipython \
                      sphinx-rtd-theme pydata-sphinx-theme sphinx-book-theme

      - name: Generate API Docs
        run: |
          cd docs/
          sphinx-apidoc -force -o ./api/ ../rose-pyforce/pyforce
          rm -f api/modules.rst
          # Automates the maxdepth change from 4 to 2
          sed -i 's/:maxdepth: [0-9]/:maxdepth: 2/g' api/pyforce.rst

      - name: Sphinx Build
        run: |
          cd docs/
          make html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
          force_orphan: false
