name: Build and Deploy Sphinx Docs

on:
  push:
    workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx ghp-import
        python -m pip install myst_parser nbsphinx sphinx_proof sphinxcontrib.bibtex==2.5.0 IPython
        python -m pip install sphinx_rtd_theme pydata_sphinx_theme sphinx_book_theme

    - name: Generate Sphinx documentation
      run: |
        cd docs/
        sphinx-apidoc --force -o ./api/. ../pyforce/pyforce
        # Optionally modify pyforce.rst here if needed
        rm api/modules.rst
        make clean
        make html

    # - name: Deploy to GitHub Pages
    #   run: |
    #     cd docs/
    #     ghp-import -n -p -f _build/html
