# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Testing pyforce

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: "3.10"
        channels: conda-forge
        use-mamba: true 

    - name: Create Conda environment
      run: |
        pip install rose-pyforce/

    - name: Activate Conda environment
      run: |
        pip install pytest
      shell: bash -l {0}

    - name: Test with pytest
      run: |
        pytest
      shell: bash -l {0}
